name: redditexample
description: A flutter application which renders a given subreddit
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  animations: ^1.0.0+5
  bloc: ^3.0.0
  common:
    path: ./common
  di:
    path: ./di
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  flutter_markdown: ^0.3.4
  presentation:
    path: ./presentation
  time: ^1.3.0
  transparent_image: ^1.0.0
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
