const emptySubreddit = r'''
{
    "kind": "Listing",
    "data": {
        "modhash": "",
        "dist": 0,
        "children": [],
        "after": "t3_fnn17n",
        "before": null
    }
}
''';

const singleEntrySubreddit = r'''
{
    "kind": "Listing",
    "data": {
        "modhash": "",
        "dist": 1,
        "children": [
            {
                "kind": "t3",
                "data": {
                    "approved_at_utc": null,
                    "subreddit": "ClimateActionPlan",
                    "selftext": "I hope everybody's doing well. If you're working from home and can, please make sure you walk around outside (but maintain a social distance of 6 feet minimum.) \n\nOne glimmer of good news we can take from this situation is that we will see a reduction in carbon emissions. Nowhere near as many people are driving to work now, or flying. Same can probably be said for people on cruises as well. Even if this only goes on for a few months, this is still a much needed reduction in CO2. Of course when quarantines are lifted trips that were cancelled will resume, however by the end of this year there will still be a noticeable drop in overall emissions.",
                    "author_fullname": "t2_1bjvt3jo",
                    "saved": false,
                    "mod_reason_title": null,
                    "gilded": 0,
                    "clicked": false,
                    "title": "One bit of good news to take from the COVID-19 outbreak.",
                    "link_flair_richtext": [],
                    "subreddit_name_prefixed": "r/ClimateActionPlan",
                    "hidden": false,
                    "pwls": 6,
                    "link_flair_css_class": null,
                    "downs": 0,
                    "thumbnail_height": null,
                    "hide_score": false,
                    "name": "t3_fkvbje",
                    "quarantine": false,
                    "link_flair_text_color": "dark",
                    "author_flair_background_color": "#dadada",
                    "subreddit_type": "public",
                    "ups": 42,
                    "total_awards_received": 0,
                    "media_embed": {},
                    "thumbnail_width": null,
                    "author_flair_template_id": "d5537128-88e7-11e9-a3d3-0e4624f35dc2",
                    "is_original_content": false,
                    "user_reports": [],
                    "secure_media": null,
                    "is_reddit_media_domain": false,
                    "is_meta": false,
                    "category": null,
                    "secure_media_embed": {},
                    "link_flair_text": null,
                    "can_mod_post": false,
                    "score": 42,
                    "approved_by": null,
                    "author_premium": true,
                    "thumbnail": "self",
                    "edited": false,
                    "author_flair_css_class": null,
                    "author_flair_richtext": [],
                    "gildings": {},
                    "content_categories": null,
                    "is_self": true,
                    "mod_note": null,
                    "created": 1584587919.0,
                    "link_flair_type": "text",
                    "wls": 6,
                    "removed_by_category": null,
                    "banned_by": null,
                    "author_flair_type": "text",
                    "domain": "self.ClimateActionPlan",
                    "allow_live_comments": false,
                    "selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I hope everybody&amp;#39;s doing well. If you&amp;#39;re working from home and can, please make sure you walk around outside (but maintain a social distance of 6 feet minimum.) &lt;/p&gt;\n\n&lt;p&gt;One glimmer of good news we can take from this situation is that we will see a reduction in carbon emissions. Nowhere near as many people are driving to work now, or flying. Same can probably be said for people on cruises as well. Even if this only goes on for a few months, this is still a much needed reduction in CO2. Of course when quarantines are lifted trips that were cancelled will resume, however by the end of this year there will still be a noticeable drop in overall emissions.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "likes": null,
                    "suggested_sort": null,
                    "banned_at_utc": null,
                    "view_count": null,
                    "archived": false,
                    "no_follow": false,
                    "is_crosspostable": false,
                    "pinned": false,
                    "over_18": false,
                    "all_awardings": [],
                    "awarders": [],
                    "media_only": false,
                    "can_gild": false,
                    "spoiler": false,
                    "locked": false,
                    "author_flair_text": "Mod/Creator",
                    "visited": false,
                    "removed_by": null,
                    "num_reports": null,
                    "distinguished": null,
                    "subreddit_id": "t5_ne8p6",
                    "mod_reason_by": null,
                    "removal_reason": null,
                    "link_flair_background_color": "",
                    "id": "fkvbje",
                    "is_robot_indexable": true,
                    "report_reasons": null,
                    "author": "UT_Teapot",
                    "discussion_type": null,
                    "num_comments": 9,
                    "send_replies": true,
                    "whitelist_status": "all_ads",
                    "contest_mode": false,
                    "mod_reports": [],
                    "author_patreon_flair": false,
                    "author_flair_text_color": "dark",
                    "permalink": "/r/ClimateActionPlan/comments/fkvbje/one_bit_of_good_news_to_take_from_the_covid19/",
                    "parent_whitelist_status": "all_ads",
                    "stickied": true,
                    "url": "https://www.reddit.com/r/ClimateActionPlan/comments/fkvbje/one_bit_of_good_news_to_take_from_the_covid19/",
                    "subreddit_subscribers": 60887,
                    "created_utc": 1584559119.0,
                    "num_crossposts": 0,
                    "media": null,
                    "is_video": false
                }
            }
        ],
        "after": "t3_fnn17n",
        "before": null
    }
}
''';
