name: remote
description: Remote layer responsible of fetching data from remote data source

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  common:
    path: ../common
  data:
    path: ../data
  dio: ^3.0.9
  flutter:
    sdk: flutter
  http: 0.12.0+4
  json_annotation: ^3.0.0
  retrofit: ^1.3.1+1
  time: ^1.3.0

dev_dependencies:
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  mock_web_server: ^4.1.1
  retrofit_generator: ^1.3.1+9
  test: any
